### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by hyunjiLeeTech** [upsetdog/wanikani-notifier#9]
There's no package-lock.json file in this project so users need to install modules manually checking what modules are needed for this project. It would be better if package-lock.json file is included on this project so users can simply install modules when they enter 'npm install'. 
I would like to take this and update the README file as well.

**Comment by upsetdog** [comment]
oh yes go for it, thank u

**Comment by hyunjiLeeTech** [comment]
I've done this. Can you please check my pull request?
